-- Migration: fix_activity_log_id_default
-- Description: This migration ensures that the `id` column of the `activity_log` table has a default value generated by the `uuid-ossp` extension.

-- Enable the uuid-ossp extension if it's not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Alter the activity_log table to set the default value for the id column
ALTER TABLE "activity_log" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4();
